baskCart/urls.py
from django.urls import path
from . import views

app_name = 'baskCart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/(<product_id>)', views.cart_add, name='cart_add'),
    path('remove/(P<product_id>)', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_create_user/', views.order_create_user, name='order_create_user'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include("firstApp.urls")),
    path('admin/', admin.site.urls),
    path('baskCart/', include("baskCart.urls", namespace='baskCart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baskCart/models.py
from django.db import models

# Create your models here.

baskCart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


baskCart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .baskCart import Cart
from .forms import CartAddProductForm
from firstApp.models import Product
from firstApp.views import base


# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        return redirect('baskCart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('baskCart:cart_detail')

def cart_detail(request):
    baskCart = Cart(request)
    context = {'baskCart': baskCart}
    context.update(base())
    return render(request, 'baskCart/detail.html', context)

templates/baskCart/detail.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">

    <h1 class="reg__head">Корзина</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Картинка</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за единицу</th>
            <th>Конечная цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in baskCart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{% url 'productCart' id=product.pk name=product.name %}">
                            <img src="{{ product.images.url }}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a class="btn btn-danger" href="{% url "baskCart:cart_remove" product.id%}">Удалить</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">${{ baskCart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'index' %}" class="btn btn-primary">Continue shopping</a>
        {% if user.is_authenticated %}
        <a href="{% url "orders:order_create_user" %}" class="btn btn-primary">
            Оформить заказ в один клилк
        </a>
        {% else %}
        <a href="{% url "orders:order_create" %}" class="btn btn-primary">
            Оформить заказ
        </a>
        {% endif %}
    </p>

</div>
{% endblock %}