orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_create_user/', views.order_create_user, name='order_create_user'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include("firstApp.urls")),
    path('admin/', admin.site.urls),
    path('baskCart/', include("baskCart.urls", namespace='baskCart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
# Create your models here.
from firstApp.models import Product
from firstApp.models import Profile

class OrderUser(models.Model):
    user = models.ForeignKey(Profile, verbose_name='Пользователь', on_delete=models.CASCADE)
    state = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Order {}'.format(self.id)

    class Meta:
        verbose_name = 'Заказ от пользователя'
        verbose_name_plural = 'Заказы от пользователей'

class OrderItemUser(models.Model):
    order = models.ForeignKey(OrderUser, related_name='items_user', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items_user', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


orders/forms.py
import telegram
from django import forms
from .models import Order, OrderUser


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

    async def send_message(self):
        bot_token = '6509764574:AAHh5VRUaka14LuoFav-DLmrNyADFp7K9N4'
        chat_id = -1002124719444
        # chat_id = -768487653
        bot = telegram.Bot(token=bot_token)
        message_text = f"""Имя: {self.cleaned_data['first_name']}
        Фамилия: {self.cleaned_data['last_name']}
        Почта: {self.cleaned_data['email']}
        Адрес: {self.cleaned_data['address']}
        Почтовый индекс: {self.cleaned_data['postal_code']}
        Город: {self.cleaned_data['city']}
        """
        await bot.send_message(chat_id=chat_id, text=message_text)

class OrderUserCreateForm(forms.ModelForm):
    class Meta:
        model = OrderUser
        fields = ['user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user

#     async def send_message_user(self):
#         bot_token = '6509764574:AAHh5VRUaka14LuoFav-DLmrNyADFp7K9N4'
#         chat_id = -1002124719444
#         # chat_id = -768487653
#         bot = telegram.Bot(token=bot_token)
#         message_text = f"""------------------
#         Пользователь: {self.cleaned_data['user']}
# ------------------"""
#         await bot.send_message_user(chat_id=chat_id, text=message_text)

orders/views.py
from django.shortcuts import render
# Create your views here.
from .models import OrderItem, OrderItemUser
from .forms import OrderCreateForm, OrderUserCreateForm
from baskCart.baskCart import Cart
from firstApp.views import base
import asyncio


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        # print(form.errors)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            asyncio.run(form.send_message())
            context = {'order': order}
            context.update(base())
            return render(request, 'orders/created.html', context)
    else:
        form = OrderCreateForm
    context = {'cart': cart, 'form': form}
    context.update(base())
    return render(request, 'orders/create.html', context)

def order_create_user(request):
    cart = Cart(request)
    if request.method == 'POST':
        formUser = OrderUserCreateForm(request.POST, user=request.user)
        print(formUser.errors)
        if formUser.is_valid():
            order = formUser.save()
            for item in cart:
                OrderItemUser.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            # asyncio.run(formUser.send_message_user())
            context = {'order': order}
            context.update(base())
            return render(request, 'orders/created.html', context)
    else:
        formUser = OrderUserCreateForm
    context = {'cart': cart, 'formUser':formUser}
    context.update(base())
    return render(request, 'orders/create_user.html', context)

templates/orders/create.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">
    <style>
        .order-form{
            max-width: 600px;
        }
        .input-group{
            margin-bottom: 10px;
            grid-gap: 10px;
        }
    </style>
    <h1>Заявка:</h1>
    <div class="d-flex">
        <div class="p-2 w-100">
            <form action="." method="POST" class="order-form">
                {% csrf_token %}
<!--                {{ form.as_p }}-->
                    <div class="input-group flex-nowrap">
                        <input name="first_name" type="text" class="form-control" placeholder="Имя">
                        <input name="last_name" type="text" class="form-control" placeholder="Фамилия">
                    </div>
                    <div class="input-group flex-nowrap">
                        <input name="email" type="email" class="form-control" placeholder="email">
                    </div>
                    <div class="input-group flex-nowrap">
                        <input name="address" type="text" class="form-control" placeholder="Адрес">
                        <input name="postal_code" type="text" class="form-control" placeholder="Почтовый индекс">
                        <input name="city" type="text" class="form-control" placeholder="Город">
                    </div>
                <button type="submit" class="btn btn-success">Разместить заказ</button>
            </form>
        </div>
        <div class="p-2 flex-shrink-1">
            <div class="order-info card">
            <h3 class="card-header">Ваш заказ</h3>
            <ul class="list-group">
                {% for item in cart %}
                    <li class="list-group-item card-text">
                        {{ item.quantity }}x {{ item.product.name }}
                        <p class="text-end">${{ item.total_price }}</p>
                    </li>
                {% endfor %}
            </ul>
            <p>Всего: ${{ cart.get_total_price }}</p>
        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/orders/create_user.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">
    <style>
        .order-form{
            max-width: 600px;
        }
        .input-group{
            margin-bottom: 10px;
            grid-gap: 10px;
        }
    </style>
    <h1>Заявка:</h1>
    <div class="d-flex">
        <div class="p-2 w-100">
            <form action="." method="POST" class="order-form">
                {% csrf_token %}
<!--                {{ formUser.as_p }}-->
                    <div class="input-group flex-nowrap">
                        <select hidden="hidden" name="user" required="" aria-invalid="true" id="id_user">
                          <option value="">---------</option>
                          <option value="1" selected>{{ user.username }}</option>
                        </select>
                        <p>Имя: {{ user.username }}</p>
                    </div>
                    <div class="input-group flex-nowrap">
                        <p>Email: {{ user.email }}</p>
                    </div>
                    <div class="input-group flex-nowrap">
                        <p>Адрес: {{ user.profile.address }}</p>
                    </div>
                    <div class="input-group flex-nowrap">
                        <p>Почтовый индекс: {{ user.profile.mail_index }}</p>
                    </div>
                    <div class="input-group flex-nowrap">
                        <p>Город: {{ user.profile.city }}</p>
                    </div>
                    <div class="input-group flex-nowrap">
                        <p>Телефон: {{ user.profile.phone }}</p>
                    </div>
                    <p style="color: red; font-size: 11px;">Для размещения заказа обязательно заполните данные профиля</p>
                <button type="submit" class="btn btn-success">Разместить заказ</button>
            </form>
        </div>
        <div class="p-2 flex-shrink-1">
            <div class="order-info card">
            <h3 class="card-header">Ваш заказ</h3>
            <ul class="list-group">
                {% for item in cart %}
                    <li class="list-group-item card-text">
                        {{ item.quantity }}x {{ item.product.name }}
                        <p class="text-end">${{ item.total_price }}</p>
                    </li>
                {% endfor %}
            </ul>
            <p>Всего: ${{ cart.get_total_price }}</p>
        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/orders/created.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">
    <h1>Спасибо</h1>
    <p>Ваш заказ был оформлен успешно. Номер вашего заказа.
        <strong>{{ order.id }}</strong>.</p>
    <p>
        С вами свяжется наш менеджер для уточнения деталей заказа
    </p>
</div>
{% endblock %}