baskCart/urls.py
from django.urls import path
from . import views

app_name = 'baskCart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/(<product_id>)', views.cart_add, name='cart_add'),
    path('remove/(P<product_id>)', views.cart_remove, name='cart_remove'),
]

firstApp/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("catalog/<str:name>", views.catalog, name="catalog"),
    path("contact/", views.contact, name="contact"),
    path("news/", views.news, name="news"),
    path("registr/", views.registr, name="registr"),
    path("login_User/", views.login_User, name="login_User"),
    path("profile/", views.profile, name="profile"),
    path("productCart/<int:id>/<str:name>", views.productCart, name="productCart"),
    path('remove_favorite/<int:id>', views.remove_favorite, name='remove_favorite'),
    path('search', views.search, name="search"),
    path("logout", views.logoutView, name="account_logout"),
    path("newsPost/<int:id>/<str:title>", views.newsPost, name="newsPost"),
#прочие urls
    path("company/", views.company, name="company"),
    path("services/", views.services, name="services"),
    path("serviceRepair/", views.serviceRepair, name="serviceRepair"),
    path("wholesale/", views.wholesale, name="wholesale"),
    path("faq/", views.faq, name="faq"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_create_user/', views.order_create_user, name='order_create_user'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include("firstApp.urls")),
    path('admin/', admin.site.urls),
    path('baskCart/', include("baskCart.urls", namespace='baskCart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstApp/forms.py
from django import forms
import telegram
from django.contrib.auth.models import User

from .models import FeaturedProducts, Product, Shipping, Payment, Comment


# FeedbackForm ========================================================
class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=12)
    message = forms.CharField(widget=forms.Textarea)

    async def send_message(self):
        bot_token = '6509764574:AAHh5VRUaka14LuoFav-DLmrNyADFp7K9N4'
        chat_id = -1002124719444
        # chat_id = -768487653
        bot = telegram.Bot(token=bot_token)
        message_text = f"Name: {self.cleaned_data['name']}\nPhone: {self.cleaned_data['phone']}\nMessage: {self.cleaned_data['message']}"
        await bot.send_message(chat_id=chat_id, text=message_text)

# FeedbackForm ========================================================

# RegisterForm ========================================================
class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    phone = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'reg__input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2', 'phone')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


# RegisterForm ========================================================


# FavoriteForm=========================================================
class FavoriteForm(forms.ModelForm):
    # featuredProducts_User = forms
    class Meta:
        model = FeaturedProducts
        fields = ['featuredProducts_User', 'featuredProducts_Product']
        widgets = {
            'featuredProducts_User': forms.HiddenInput(),
            'featuredProducts_Product': forms.HiddenInput(),
        }


# FavoriteForm=========================================================



# upload user form ====================================================
class CombinedForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    address = forms.CharField()
    preferredPaymentMethod = forms.ModelChoiceField(queryset=Payment.objects.all(), required=False)
    phone = forms.IntegerField()
    preferredShippingMethod = forms.ModelChoiceField(queryset=Shipping.objects.all(), required=False)
    city = forms.CharField()
    avatar = forms.ImageField()
    mail_index = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(CombinedForm, self).__init__(*args, **kwargs)
        self.fields['address'].initial = self.instance.profile.address
        self.fields['preferredPaymentMethod'].initial = self.instance.profile.preferredPaymentMethod
        self.fields['phone'].initial = self.instance.profile.phone
        self.fields['preferredShippingMethod'].initial = self.instance.profile.preferredShippingMethod
        self.fields['city'].initial = self.instance.profile.city
        self.fields['avatar'].initial = self.instance.profile.avatar
        self.fields['mail_index'].initial = self.instance.profile.mail_index

    def save(self, commit=True):
        user = super(CombinedForm, self).save(commit=False)
        profile = user.profile
        profile.address = self.cleaned_data['address']
        profile.preferredPaymentMethod = self.cleaned_data['preferredPaymentMethod']
        profile.phone = self.cleaned_data['phone']
        profile.preferredShippingMethod = self.cleaned_data['preferredShippingMethod']
        profile.city = self.cleaned_data['city']
        profile.avatar = self.cleaned_data['avatar']
        profile.mail_index = self.cleaned_data['mail_index']
        if commit:
            user.save()
            profile.save()
        return user


# upload user form ====================================================


# upload password form ================================================
class Re_Password(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_NewPassword = forms.CharField(label='New Password', widget=forms.PasswordInput)
    password_NewPassword2 = forms.CharField(label='Repeat New password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('password', 'password_NewPassword', 'password_NewPassword2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password_NewPassword'] != cd['password_NewPassword2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password_NewPassword2']

    def save(self, user):
        user_to_update = User.objects.get(id=user.id)
        user_to_update.set_password(self.cleaned_data['password_NewPassword2'])
        user_to_update.save()
        return user_to_update
# upload password form ================================================

# CommentForm =========================================================
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('user', 'published_date', 'product')
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
# CommentForm =========================================================

firstApp/views.py
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.timezone import now
import asyncio

from .forms import RegisterForm, FavoriteForm, CombinedForm, Re_Password, CommentForm, FeedbackForm
from .models import Product, MainSlider, Leaders, News, Tegs, Catalog, Profile, FeaturedProducts, ProductImagesDescr, \
    Comment
from baskCart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def base():
    catalogList = Catalog.objects.all().order_by("pk")
    productGiro = Product.objects.all()
    cart_product_form = CartAddProductForm()
    context = {'catalogList': catalogList, 'productGiro': productGiro, 'cart_product_form': cart_product_form}
    return context


def index(request):
    # productGiro = Product.objects.all()
    mainSlider = MainSlider.objects.all()
    leaders = Leaders.objects.all()
    news = News.objects.all().order_by("-published_date")
    context = {"mainSlider": mainSlider, "leaders": leaders, "news": news}
    context.update(base())
    return render(request, 'firstApp/index.html', context)


def search(request):
    query = request.GET.get('query')
    product = Product.objects.filter(Q(descriptions__icontains=query) | Q(name__icontains=query))
    order_by = request.GET.get('order_by')
    if order_by:
        product = product.order_by(order_by)
    context = {"product": product, "query": query}
    context.update(base())
    return render(request, 'firstApp/catalog.html', context)


def catalog(request, name=None):
    try:
        c = get_object_or_404(Catalog, name=name)
        tegs = Tegs.objects.filter(category=c)
        products = Product.objects.filter(category=c)
        order_by = request.GET.get('order_by')
        if order_by:
            products = products.order_by(order_by)
        paginator = Paginator(products, 9)
        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context = {'product': products, 'teg': tegs, 'c': c}
    except BaseException:
        c_с = get_object_or_404(Tegs, name=name)
        tegs = Tegs.objects.all()
        category = Catalog.objects.all()
        products = Product.objects.filter(tegs=c_с)
        order_by = request.GET.get('order_by')
        if order_by:
            products = products.order_by(order_by)
        paginator = Paginator(products, 9)
        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context = {'product': products, 'teg': tegs, 'c_с': c_с, 'category': category}
    context.update(base())
    return render(request, 'firstApp/catalog.html', context)


def contact(request):
    if request.method == 'POST':
        fead_back_form = FeedbackForm(request.POST)
        if fead_back_form.is_valid():
            asyncio.run(fead_back_form.send_message())
            return redirect('contact')
    else:
        fead_back_form = FeedbackForm()
    context = {'fead_back_form': fead_back_form}
    context.update(base())
    return render(request, 'firstApp/contact.html', context)


def productCart(request, id=None, name=None):
    try:
        product = get_object_or_404(Product, id=id, name=name)
        imgProductDesc = ProductImagesDescr.objects.all()
        comment = Comment.objects.filter(product=id).order_by("-published_date")
        profile = Profile.objects.get(user=request.user)
        is_favorite = FeaturedProducts.objects.filter(featuredProducts_User=profile,
                                                      featuredProducts_Product=product).exists()
        if request.method == 'POST':
            form_Favorite = FavoriteForm(request.POST)
            form_Comment = CommentForm(request.POST)
            if form_Comment.is_valid():
                comment = form_Comment.save(commit=False)
                comment.published_date = now()
                comment.product = product
                comment.user = request.user
                comment.save()
                return redirect('productCart', id=product.id, name=product.name)
            elif form_Favorite.is_valid():
                form_Favorite.instance.featuredProducts_User = profile
                form_Favorite.instance.featuredProducts_Product = product
                form_Favorite.save()
                return redirect('productCart', id=product.id, name=product.name)
        else:
            form_Comment = CommentForm()
            form_Favorite = FavoriteForm()
        context = {'product': product, 'form_Favorite': form_Favorite, 'is_favorite': is_favorite,
                   'imgProductDesc': imgProductDesc, 'comment': comment, 'form_Comment': form_Comment}
    except BaseException:
        product = get_object_or_404(Product, id=id, name=name)
        imgProductDesc = ProductImagesDescr.objects.all()
        comment = Comment.objects.filter(product=id).order_by("-published_date")
        context = {'product': product, 'imgProductDesc': imgProductDesc, 'comment': comment}
    context.update(base())
    return render(request, 'firstApp/product-cart.html', context)


# резервная копия кода карточки товара
# @login_required
# def productCart(request, id=None, name=None):
#     product = get_object_or_404(Product, id=id, name=name)
#     profile = Profile.objects.get(user=request.user)
#     imgProductDesc = ProductImagesDescr.objects.all()
#     comment = Comment.objects.filter(product=id).order_by("-published_date")
#     is_favorite = FeaturedProducts.objects.filter(featuredProducts_User=profile,
#                                                   featuredProducts_Product=product).exists()
#     if request.method == 'POST':
#         form_Favorite = FavoriteForm(request.POST)
#         form_Comment = CommentForm(request.POST)
#         if form_Comment.is_valid():
#             comment = form_Comment.save(commit=False)
#             comment.published_date = now()
#             comment.product = product
#             comment.user = request.user
#             comment.save()
#             return redirect('productCart', id=product.id, name=product.name)
#         elif form_Favorite.is_valid():
#             form_Favorite.instance.featuredProducts_User = profile
#             form_Favorite.instance.featuredProducts_Product = product
#             form_Favorite.save()
#             return redirect('productCart', id=product.id, name=product.name)
#     else:
#         form_Comment = CommentForm()
#         form_Favorite = FavoriteForm()
#     context = {'product': product, 'form_Favorite': form_Favorite, 'is_favorite': is_favorite, 'imgProductDesc': imgProductDesc, 'comment': comment, 'form_Comment': form_Comment}
#     context.update(base())
#     return render(request, 'firstApp/product-cart.html', context)


@login_required
def remove_favorite(request, id=None):
    product = get_object_or_404(Product, pk=id)
    profile = Profile.objects.get(user=request.user)
    featured_product = FeaturedProducts.objects.get(featuredProducts_User=profile, featuredProducts_Product=product)
    featured_product.delete()
    return redirect('productCart', id=product.id, name=product.name)


def registr(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user, phone=form.cleaned_data['phone'])
            return redirect('login_User')
    else:
        form = RegisterForm()
    context = {'form': form}
    context.update(base())
    return render(request, 'firstApp/registr.html', context)


def profile(request):
    featuredProducts = FeaturedProducts.objects.all()
    user_Info = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        re_pass = Re_Password(request.POST)
        update_form = CombinedForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('profile')
        elif re_pass.is_valid():
            update_pass_user = re_pass.save(user=request.user)
            update_session_auth_hash(request, update_pass_user)
            return redirect('profile')
    else:
        update_form = CombinedForm(instance=request.user)
        re_pass = Re_Password(request.POST)
    context = {'user_Info': user_Info, 'featuredProducts': featuredProducts, 'update_form': update_form,
               're_pass': re_pass}
    context.update(base())
    return render(request, 'firstApp/account.html', context)


def logoutView(request):
    logout(request)
    return redirect('index')


def login_User(request):
    context = {}
    context.update(base())
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('profile')
        else:
            return render(request, 'firstApp/login.html',

templates/firstApp/ServiceRepair.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">
    <h3 class="catalog__head">Сервис и ремонт</h3>
</div>
{% endblock %}

templates/firstApp/faq.html
{% extends "firstApp/base.html" %}
{% block content %}
<div class="container">
    <h3 class="catalog__head">F.A.Q.</h3>
</div>
{% endblock %}

templates/firstApp/pagination.html

<ul class="pager">
    <li class="previous">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">&larr; Older</a>
        {% endif %}
    </li>
    <span>Page {{ page.number }} of {{ page.paginator.num_pages }} </span>
    <li class="next">
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Newer &rarr;</a>
        {% endif %}
    </li>
</ul>

templates/firstApp/product-cart.html
{% extends "firstApp/base.html" %}
{% block content%}
<style>
.product-cart__slider-wrapp {
    left: 120px;
}
.product-cart__reviews-inner-user {
    margin-bottom: 20px;
}
</style>
        <section class="product-cart">
            <div class="container">
                <h3 class="product-cart__head">{{ product.name }}</h3>
                <div class="product-cart__first-box">
                    <div width="100px" class="product-cart__slider-nav-wrapp">
                        <div class="product-cart__slider-nav">
                        {% for imgs in product.imagesDescr.all %}
                            <div width="100px" class="product-cart__slider-img">
                                <img width="100px" src="{{ imgs.images.url }}" alt="images" class="product-cart__nav-img">
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                    <div class="product-cart__slider-wrapp">
                        <div class="product-cart__slider">
                            {% for imgs in product.imagesDescr.all %}
                            <div width="300px" class="product-cart__slider-img">
                                <img src="{{ imgs.images.url }}" alt="images" class="product-cart__images">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="product-cart__inf">
                        <span class="product-cart__inf-other-text">Доставка и пукнты выдачи</span>
                        <div class="product-cart__inf-price-box">
                            <span class="product-cart__inf-price">{{ product.newPrice }} $</span>
                        {% if product.sale > 0 %}
                            <span class="product-cart__inf-old-price">{{ product.price }} $</span>
                            <div class="product-cart__sale-box">
                                <p class="product-cart__sale-perc">{{ product.sale }}%</p>
                                <p class="product-cart__sale-numb">{{ product.differencePrice }} $</p>
                            </div>
                        {% endif %}
                        </div>
                        <span class="product-cart__marc fas fa-truck">Доставка — 1 $ </span>
                        <p class="product-cart__inf-text">11 июня (послезавтра)</p>
                        <span class="product-cart__marc fas fa-map-marker-alt">Пункты выдачи — 1 $ </span>
                        <p class="product-cart__inf-text">12 июня (сб)</p>
                        <span class="product-cart__marc far fa-credit-card">Оплата</span>
                        <p class="product-cart__inf-text">-Онлайн</p>
                        <p class="product-cart__inf-text">-При получении</p>
                        <form action="{% url 'baskCart:cart_add' product.id %}" method="POST">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <button type="submit" class="product-cart__btn-bask sells__cart-inbask">В корзину</button>
                        </form>
                    {% if user.is_authenticated %}
                        {% if is_favorite %}
                        <form method="POST" action="{% url 'remove_favorite' id=product.id %}">
                            {% csrf_token %}
                            {{ form_Favorite.as_p }}
                            <button type="submit" class="product-cart__btn-bask sells__cart-inbask">Убрать из избранного</button>
                        </form>
                        {% else %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ form_Favorite.as_p }}
                            <button type="submit" class="product-cart__btn-bask sells__cart-inbask">В избранное</button>
                        </form>
                        {% endif %}
                    {% endif %}

                    </div>
                </div>
                <div class="product-cart">
                    <h3 class="product-cart__head fas fa-chevron-down">Описание</h3>
                    <p class="product-cart__description-text">{{ product.descriptions }}</p>
                </div>
                <div class="product-cart">
                    <h3 class="product-cart__head fas fa-chevron-down">Характеристики</h3>
                    <div class="product-cart__specification">
                        <div class="product-cart__specification-wrapp">
                            <h4 class="product-cart__specification-head">Корпус</h4>
                            <div class="product-cart__specification-inf">
                                <p class="product-cart__specification-text-1">Пол:</p>
                                <p class="product-cart__specification-text-2">мужской</p>
                                <p class="product-cart__specification-text-1">Максимальная нагрузка, в килограммах:</p>
                                <p class="product-cart__specification-text-2">120</p>
                                <p class="product-cart__specification-text-1">Суммарная мощность электродвигателей, в ваттах:</p>
                                <p class="product-cart__specification-text-2">700</p>
                                <p class="product-cart__specification-text-1">Максимальная скорость, в километрах в час:</p>
                                <p class="product-cart__specification-text-2">15</p>
                            </div>
                        </div>
                        <div class="product-cart__specification-wrapp">
                            <h4 class="product-cart__specification-head">Корпус</h4>
                            <div class="product-cart__specification-inf">
                                <p class="product-cart__specification-text-1">Пол:</p>
                                <p class="product-cart__specification-text-2">мужской</p>
                                <p class="product-cart__specification-text-1">Максимальная нагрузка, в килограммах:</p>
                                <p class="product-cart__specification-text-2">120</p>
                                <p class="product-cart__specification-text-1">Суммарная мощность электродвигателей, в ваттах:</p>
                                <p class="product-cart__specification-text-2">700</p>
                                <p class="product-cart__specification-text-1">Максимальная скорость, в километрах в час:</p>
                                <p class="product-cart__specification-text-2">15</p>
                            </div>
                        </div>
                        <div class="product-cart__specification-wrapp">
                            <h4 class="product-cart__specification-head">Аккумулятор</h4>
                            <div class="product-cart__specification-inf">
                                <p class="product-cart__specification-text-1">Пол:</p>
                                <p class="product-cart__specification-text-2">мужской</p>
                                <p class="product-cart__specification-text-1">Максимальная нагрузка, в килограммах:</p>
                                <p class="product-cart__specification-text-2">120</p>
                                <p class="product-cart__specification-text-1">Суммарная мощность электродвигателей, в ваттах:</p>
                                <p class="product-cart__specification-text-2">700</p>
                                <p class="product-cart__specification-text-1">Максимальная скорость, в километрах в час:</p>
                                <p class="product-cart__specification-text-2">15</p>
                            </div>
                        </div>
                        <div class="product-cart__specification-wrapp">
                            <h4 class="product-cart__specification-head">Аккумулятор</h4>
                            <div class="product-cart__specification-inf">
                                <p class="product-cart__specification-text-1">Пол:</p>
                                <p class="product-cart__specification-text-2">мужской</p>
                                <p class="product-cart__specification-text-1">Максимальная нагрузка, в килограммах:</p>
                                <p class="product-cart__specification-text-2">120</p>
                                <p class="product-cart__specification-text-1">Суммарная мощность электродвигателей, в ваттах:</p>
                                <p class="product-cart__specification-text-2">700</p>
                                <p class="product-cart__specification-text-1">Максимальная скорость, в километрах в час:</p>
                                <p class="product-cart__specification-text-2">15</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="product-cart product-cart__sells">
                    <h3 class="product-cart__head">Похожие товары</h3>
                    <div class="sells__wrapp-product">
                        {% for productGiro in productGiro %}
                            {% if product.tegs == productGiro.tegs %}
                                {% if forloop.counter <= 4 %}
                                    {% include "firstApp/miniProductCart.html" %}
                                {% endif %}
                            {% endif %}
                       {% endfor %}
                    </div>
                </div>
                <div class="product-cart">
                    <div class="product-cart__reviews-box-top">
                        <h3 class="product-cart__head product-cart__head-reviews fas fa-chevron-down">Отзывы</h3>
<!--                        <div class="product-cart__reviews-box-btn">-->
<!--                            <button class="product-cart__reviews-btn-one">Оставить отзыв</button>-->
<!--                            <button class="product-cart__reviews-btn-two">Все отзывы</button>-->
<!--                        </div>-->
                    </div>
                {% if user.is_authenticated %}

                    <div class="well">
                        <h4>Оставить отзыв:</h4>
                        <form role="form" method="POST" action="{% url 'productCart' id=product.id name=product.name %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <textarea required name="commentText" class="form-control" rows="3"></textarea>
                            </div>
                            <button type="submit" value="save" class="btn btn-primary">отзыв</button>
                        </form>
                    </div>
                {% endif %}

                    <hr>
                    <div class="product-cart__reviews-box-wrapp">
                        <div class="product-cart__reviews-inner">
                            {% for comment in comment %}
                                <div class="product-cart__reviews-inner-user">
                                    <img class="media-object" src="{{ comment.user.profile.avatar.url }}" alt="" width="50px">
                                    <div class="product-cart__reviews-user-name">
                                        <p class="product-cart__reviews-user-name-text">{{ comment.user.username }}</p>
                                    </div>
                                    <div class="product-cart__reviews-user-date-box">
                                        <span class="product-cart__reviews-user-date">{{ comment.published_date }}</span>
                                    </div>
                                    <div class="product-cart__reviews-user-grade-box">
                                        <span class="product-cart__reviews-user-grade-text">Оценка: </span>
                                        <div class="product-cart__reviews-user-grade-wrapp">
                                            <div class="product-cart__reviews-user-grade fas fa-star"></div>
                                            <div class="product-cart__reviews-user-grade fas fa-star"></div>
                                            <div class="product-cart__reviews-user-grade fas fa-star"></div>
                                            <div class="product-cart__reviews-user-grade fas fa-star"></div>
                                            <div class="product-cart__reviews-user-grade fas fa-star"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-cart__reviews-content">
                                    <div class="product-cart__reviews-content-box">
                                        <span class="product-cart__reviews-span">{{ comment.commentText }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}